<center><h1>Numpy hidden Functions</h1></center>

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

np.sort kyu use kar rhe hai  
kyuki agr python ka sorted use karenge too python ka list milega  
But np.sort se numpy ka array milega

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([35, 93, 61, 60, 24, 85, 69, 36, 14,  5, 43, 95, 45, 17, 21])

In [17]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[ 4, 10, 17, 21],
       [24, 31, 32, 71],
       [80, 89, 80, 92],
       [97, 84, 44, 64],
       [63, 73, 21, 50],
       [93, 95, 65,  8]])

In [3]:
np.sort(a)

array([ 5, 14, 17, 21, 24, 35, 36, 43, 45, 60, 61, 69, 85, 93, 95])

In [4]:
np.sort(b) # row wise sorting

array([[43, 50, 74, 96],
       [ 2, 18, 69, 82],
       [17, 52, 61, 89],
       [18, 28, 51, 57],
       [25, 64, 67, 83],
       [33, 56, 77, 91]])

In [5]:
np.sort(b, axis = 0) # column wise sorting

array([[ 2, 25, 51, 18],
       [17, 33, 52, 18],
       [28, 57, 64, 50],
       [43, 69, 74, 56],
       [67, 89, 82, 61],
       [77, 96, 91, 83]])

In [7]:
np.sort(b)[::-1] # for decreasing order sorting

array([[33, 56, 77, 91],
       [25, 64, 67, 83],
       [18, 28, 51, 57],
       [17, 52, 61, 89],
       [ 2, 18, 69, 82],
       [43, 50, 74, 96]])

Here are detailed notes on `np.sort` in NumPy:

---

# `np.sort()` in NumPy – Hidden Function Explained

## Overview
`np.sort()` is a NumPy function used to sort elements in an array along a specified axis. It does **not** modify the original array (returns a sorted copy) unless explicitly asked to do so.

## Syntax:
```python
np.sort(a, axis=-1, kind='quicksort', order=None)
```

## Parameters:
1. **a**: The input array to be sorted.
2. **axis** (default `-1`): 
   - `axis=0` → Sort column-wise (vertical sorting)
   - `axis=1` → Sort row-wise (horizontal sorting)
   - `axis=None` → Flatten the array and sort everything
3. **kind** (Sorting Algorithm):
   - `'quicksort'` (default) → Fast, but not stable.
   - `'mergesort'` → Stable (preserves order of equal elements).
   - `'heapsort'` → Slower, but works well in limited memory.
   - `'stable'` → Ensures equal elements maintain their order.
4. **order**: Used for sorting structured arrays.

---

## Sorting in 1D Array:
```python
import numpy as np

arr = np.array([5, 2, 9, 1, 5, 6])
sorted_arr = np.sort(arr)

print(sorted_arr)  # Output: [1 2 5 5 6 9]
```

---

## Sorting in 2D Array (Row-wise and Column-wise)
```python
arr_2d = np.array([[8, 3, 1], [5, 2, 9]])
print("Original:\n", arr_2d)

sorted_rows = np.sort(arr_2d, axis=1)  # Sort along rows
print("Row-wise:\n", sorted_rows)

sorted_cols = np.sort(arr_2d, axis=0)  # Sort along columns
print("Column-wise:\n", sorted_cols)
```

### Output:
```
Original:
 [[8 3 1]
  [5 2 9]]

Row-wise:
 [[1 3 8]
  [2 5 9]]

Column-wise:
 [[5 2 1]
  [8 3 9]]
```

---

## Sorting with `axis=None` (Flattened Sorting)
```python
arr = np.array([[3, 1, 4], [5, 9, 2]])
sorted_flat = np.sort(arr, axis=None)
print(sorted_flat)  # Output: [1 2 3 4 5 9]
```

---

## Sorting in Descending Order:
NumPy doesn’t provide a direct descending sort, but you can reverse the result:
```python
arr = np.array([5, 2, 9, 1, 5, 6])
sorted_desc = np.sort(arr)[::-1]
print(sorted_desc)  # Output: [9 6 5 5 2 1]
```

For multidimensional sorting:
```python
sorted_desc_2d = np.sort(arr_2d, axis=1)[:, ::-1]  # Reverse sorted rows
```

---

## Sorting a Structured Array:
For arrays with named fields:
```python
dtype = [('name', 'U10'), ('age', int)]
data = np.array([('Alice', 25), ('Bob', 22), ('Charlie', 30)], dtype=dtype)

sorted_data = np.sort(data, order='age')  # Sort by age
print(sorted_data)
```

---

## Stable Sorting:
Preserves the order of equal elements.
```python
arr = np.array([5, 2, 9, 5, 6, 2])
sorted_stable = np.sort(arr, kind='stable')
print(sorted_stable)  # Output: [2 2 5 5 6 9]
```

---

## Summary:
- `np.sort()` returns a sorted copy of an array.
- It supports different sorting algorithms (`quicksort`, `mergesort`, etc.).
- It can sort along different axes in multi-dimensional arrays.
- Use `axis=None` for global sorting.
- Reverse indexing (`[::-1]`) gives descending order.
- `stable` sorting maintains order of equal elements.

---

This covers everything about `np.sort`. Let me know if you need further explanations! 🚀

# Hidden NumPy Functions: A Comprehensive Guide to `np.sort` and Related Sorting Functions

**Table of Contents**

1. [Introduction](#introduction)
2. [Understanding Sorting in NumPy](#understanding-sorting-in-numpy)
3. [The `np.sort` Function](#the-np-sort-function)
   - [Syntax and Parameters](#syntax-and-parameters)
   - [Return Value](#return-value)
   - [Sorting Algorithms (`kind` parameter)](#sorting-algorithms-kind-parameter)
4. [Sorting Along Different Axes](#sorting-along-different-axes)
5. [In-place vs. Out-of-place Sorting](#in-place-vs-out-of-place-sorting)
   - [Using `np.sort`](#using-np-sort)
   - [Using `ndarray.sort`](#using-ndarraysort)
6. [Sorting Structured Arrays](#sorting-structured-arrays)
   - [Sorting by Field Names](#sorting-by-field-names)
7. [Related Sorting Functions in NumPy](#related-sorting-functions-in-numpy)
   - [`np.argsort`](#np-argsort)
   - [`np.lexsort`](#np-lexsort)
   - [`np.partition` and `np.argpartition`](#np-partition-and-np-argpartition)
8. [Advanced Sorting Techniques](#advanced-sorting-techniques)
   - [Custom Sorting Using `order` Parameter](#custom-sorting-using-order-parameter)
   - [Sorting Complex Numbers](#sorting-complex-numbers)
9. [Performance Considerations](#performance-considerations)
   - [Time Complexity of Sorting Algorithms](#time-complexity-of-sorting-algorithms)
   - [Choosing the Right Sorting Algorithm](#choosing-the-right-sorting-algorithm)
10. [Practical Examples and Use Cases](#practical-examples-and-use-cases)
    - [Sorting in Data Analysis](#sorting-in-data-analysis)
    - [Use in Machine Learning Preprocessing](#use-in-machine-learning-preprocessing)
11. [Common Pitfalls and How to Avoid Them](#common-pitfalls-and-how-to-avoid-them)
12. [Conclusion](#conclusion)
13. [Further Reading and References](#further-reading-and-references)

---

## Introduction

NumPy is a fundamental package for scientific computing in Python, providing support for large, multi-dimensional arrays and matrices, along with a vast library of high-level mathematical functions. While many of NumPy's functions are well-documented and widely used, some powerful features remain underutilized or less known.

One such function is `np.sort`, a versatile tool for sorting arrays that offers various sorting algorithms and customization options. This comprehensive guide delves into the details of `np.sort` and related sorting functions in NumPy, ensuring that you acquire a deep understanding of their usage, parameters, and applications.

---

## Understanding Sorting in NumPy

Sorting is a fundamental operation in data processing and analysis. In NumPy, sorting functions are designed to be efficient and to handle multi-dimensional arrays with ease. NumPy provides several sorting functions:

- `np.sort`
- `np.argsort`
- `np.lexsort`
- `np.partition`
- `np.argpartition`

Each function serves specific purposes and offers different capabilities, which we'll explore in this guide.

---

## The `np.sort` Function

`np.sort` is the primary function for sorting arrays in NumPy. It returns a sorted copy of an array.

### Syntax and Parameters

```python
numpy.sort(a, axis=-1, kind=None, order=None)
```

- **Parameters**:
  - **`a`**: array_like
    - The array to be sorted.
  - **`axis`**: int or None, optional
    - Axis along which to sort. Default is `-1` (the last axis).
    - If `None`, the flattened array is sorted.
  - **`kind`**: {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    - Sorting algorithm to use. Default is 'quicksort'.
  - **`order`**: str or list of str, optional
    - When `a` is an array with fields (structured array), this argument specifies which fields to compare first, second, etc.

### Return Value

- **`sorted_array`**: ndarray
  - A sorted copy of `a`.

### Examples

#### Sorting a 1-D Array

```python
import numpy as np

arr = np.array([3, 1, 4, 1, 5, 9, 2])
sorted_arr = np.sort(arr)
print(sorted_arr)
# Output: [1 1 2 3 4 5 9]
```

#### Sorting a 2-D Array

By default, `np.sort` sorts along the last axis (axis `-1`).

```python
arr = np.array([[3, 1, 4],
                [1, 5, 9],
                [2, 6, 5]])
sorted_arr = np.sort(arr)
print(sorted_arr)
# Output:
# [[1 3 4]
#  [1 5 9]
#  [2 5 6]]
```

Here, each row is sorted individually.

---

## Sorting Along Different Axes

The `axis` parameter controls the axis along which the sorting is performed.

- **Axis `-1`**: Sort along the last axis (default).
- **Axis `0`**: Sort each column.
- **Axis `1`**: Sort each row.

### Sorting Along Columns (Axis `0`)

```python
arr = np.array([[3, 1, 4],
                [1, 5, 9],
                [2, 6, 5]])
sorted_arr = np.sort(arr, axis=0)
print(sorted_arr)
# Output:
# [[1 1 4]
#  [2 5 5]
#  [3 6 9]]
```

### Sorting the Entire Array (Flattened)

If `axis=None`, the array is flattened before sorting.

```python
sorted_arr = np.sort(arr, axis=None)
print(sorted_arr)
# Output: [1 1 2 3 4 5 5 6 9]
```

---

## In-place vs. Out-of-place Sorting

### Using `np.sort`

- **Out-of-place**: `np.sort` returns a sorted copy of the array and does not modify the original array.

```python
arr = np.array([3, 1, 4])
sorted_arr = np.sort(arr)
print(arr)        # Original array remains unchanged
# Output: [3 1 4]
print(sorted_arr) # Sorted copy
# Output: [1 3 4]
```

### Using `ndarray.sort`

- **In-place**: The `sort` method of an ndarray sorts the array in place and returns `None`.

```python
arr = np.array([3, 1, 4])
arr.sort()
print(arr)  # Original array is now sorted
# Output: [1 3 4]
```

#### Example with 2-D Array

```python
arr = np.array([[3, 1, 4],
                [1, 5, 9],
                [2, 6, 5]])
arr.sort(axis=1)  # Sort each row in place
print(arr)
# Output:
# [[1 3 4]
#  [1 5 9]
#  [2 5 6]]
```

---

## Sorting Structured Arrays

Structured arrays (also known as record arrays) allow you to have arrays with named fields, similar to columns in a spreadsheet or database.

### Creating a Structured Array

```python
dt = np.dtype([('name', 'U10'), ('age', int)])
data = np.array([('Alice', 25), ('Bob', 30), ('Charlie', 20)], dtype=dt)
```

### Sorting by Field Names

You can sort structured arrays by specifying the `order` parameter.

```python
sorted_data = np.sort(data, order='age')
print(sorted_data)
# Output:
# [('Charlie', 20) ('Alice', 25) ('Bob', 30)]
```

#### Sorting by Multiple Fields

```python
dt = np.dtype([('name', 'U10'), ('age', int), ('height', float)])
data = np.array([('Alice', 25, 5.5),
                 ('Bob', 30, 5.8),
                 ('Charlie', 25, 5.7)], dtype=dt)

sorted_data = np.sort(data, order=['age', 'height'])
print(sorted_data)
# Output:
# [('Alice', 25, 5.5) ('Charlie', 25, 5.7) ('Bob', 30, 5.8)]
```

---

## Related Sorting Functions in NumPy

### `np.argsort`

Returns the indices that would sort an array.

#### Syntax

```python
numpy.argsort(a, axis=-1, kind=None, order=None)
```

#### Example

```python
arr = np.array([3, 1, 4, 1, 5, 9, 2])
indices = np.argsort(arr)
print(indices)
# Output: [1 3 6 0 2 4 5]
print(arr[indices])
# Output: [1 1 2 3 4 5 9]
```

### Use Case

- Finding the ranking of elements.
- Indirectly sorting other arrays based on the sorted order.

### `np.lexsort`

Performs an indirect stable sort using a sequence of keys.

#### Syntax

```python
numpy.lexsort(keys)
```

- The last key in the sequence is the primary key.

#### Example

Suppose you have two arrays representing the last names and first names:

```python
last_names = np.array(['Smith', 'Jones', 'Williams', 'Taylor'])
first_names = np.array(['Emma', 'Liam', 'Olivia', 'Noah'])
indices = np.lexsort((first_names, last_names))
print(indices)
# Output: [1 3 0 2]
print(last_names[indices])
# Output: ['Jones' 'Taylor' 'Smith' 'Williams']
print(first_names[indices])
# Output: ['Liam' 'Noah' 'Emma' 'Olivia']
```

- The data is sorted first by `last_names`, then by `first_names`.

### `np.partition` and `np.argpartition`

Partitions an array, partially sorting it so that the smallest `k` elements are moved to the left.

#### Syntax

```python
numpy.partition(a, kth, axis=-1, kind='introselect', order=None)
numpy.argpartition(a, kth, axis=-1, kind='introselect', order=None)
```

#### Example

Find the 3 smallest elements:

```python
arr = np.array([7, 2, 3, 1, 5, 6, 4])
partitioned_arr = np.partition(arr, 3)
print(partitioned_arr)
# Output: [2 1 3 4 5 6 7]
# Note: The smallest 4 elements are on the left, not necessarily sorted.

# Get indices
indices = np.argpartition(arr, 3)
print(indices)
# Output: [1 3 2 6 4 5 0]
```

---

## Advanced Sorting Techniques

### Custom Sorting Using `order` Parameter

When dealing with structured arrays, you can specify the fields to sort by using the `order` parameter.

#### Example

```python
# Assuming 'data' is a structured array with fields 'age' and 'name'
sorted_data = np.sort(data, order='name')
```

### Sorting Complex Numbers

By default, complex numbers are sorted first by their real part, then by their imaginary part.

#### Example

```python
arr = np.array([3+4j, 1+2j, 5+0j, 2+3j])
sorted_arr = np.sort(arr)
print(sorted_arr)
# Output: [1.+2.j 2.+3.j 3.+4.j 5.+0.j]
```

- To sort based on magnitude:

```python
magnitudes = np.abs(arr)
indices = np.argsort(magnitudes)
sorted_arr = arr[indices]
print(sorted_arr)
```

---

## Performance Considerations

### Time Complexity of Sorting Algorithms

NumPy offers different sorting algorithms via the `kind` parameter:

- **'quicksort'**: Average O(n log n), worst-case O(n^2). Not stable.
- **'mergesort'**: O(n log n). Stable. Preferred when stability is required.
- **'heapsort'**: O(n log n). Not stable.
- **'stable'**: Alias to 'mergesort' in NumPy versions before 1.15 and 'timsort' thereafter.

### Choosing the Right Sorting Algorithm

- Use **'quicksort'** for general-purpose sorting when the fastest average performance is desired, and stability is not important.
- Use **'mergesort'** or **'stable'** when the original order of equal elements needs to be preserved.
- Use **'heapsort'** when memory space is limited, as it requires less additional memory.

---

## Practical Examples and Use Cases

### Sorting in Data Analysis

- **Ranking Data**: Use `np.argsort` to rank data points.
- **Sorting Records**: Sort structured arrays or recarrays based on fields.

### Use in Machine Learning Preprocessing

- **Feature Selection**: Use sorting to select top features based on importance scores.
- **Data Normalization**: Sort data before applying certain normalization techniques.

---

## Common Pitfalls and How to Avoid Them

1. **Assuming In-place Sorting with `np.sort`**:
   - Remember that `np.sort` returns a sorted copy. Use `arr.sort()` for in-place sorting.

2. **Sorting Multidimensional Arrays Without Specifying Axis**:
   - Be cautious when sorting multidimensional arrays. Not specifying the correct `axis` may lead to unexpected results.

3. **Expecting Stable Sorting**:
   - By default, 'quicksort' is used, which is not stable. Use 'mergesort' or 'stable' if stability is required.

4. **Incorrect Use of `order` Parameter**:
   - The `order` parameter only applies to structured arrays with field names.

5. **Sorting Arrays with NaN Values**:
   - NaN values are treated differently by different algorithms. Ensure that NaNs are handled appropriately.

---

## Conclusion

Sorting is a fundamental operation in data manipulation, and NumPy provides robust and flexible functions for sorting arrays efficiently. Understanding the nuances of functions like `np.sort`, `np.argsort`, and `np.lexsort`, along with their parameters and options, empowers you to handle a wide array of sorting tasks in scientific computing and data analysis.

By mastering these functions and being aware of common pitfalls, you'll be better equipped to write efficient and reliable code that leverages the full capabilities of NumPy's sorting mechanisms.

---

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [8]:
np.append(a,200)

array([ 35,  93,  61,  60,  24,  85,  69,  36,  14,   5,  43,  95,  45,
        17,  21, 200])

In [19]:
np.append(b, np.ones((b.shape[0],1)), axis = 1)

array([[ 4., 10., 17., 21.,  1.],
       [24., 31., 32., 71.,  1.],
       [80., 89., 80., 92.,  1.],
       [97., 84., 44., 64.,  1.],
       [63., 73., 21., 50.,  1.],
       [93., 95., 65.,  8.,  1.]])

In [20]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[ 4.        , 10.        , 17.        , 21.        ,  0.65472337],
       [24.        , 31.        , 32.        , 71.        ,  0.36906764],
       [80.        , 89.        , 80.        , 92.        ,  0.29902707],
       [97.        , 84.        , 44.        , 64.        ,  0.33663791],
       [63.        , 73.        , 21.        , 50.        ,  0.6449111 ],
       [93.        , 95.        , 65.        ,  8.        ,  0.14208844]])

Here are detailed and complete notes on **`np.append()`** in NumPy, covering all aspects, including maintaining array shape.

---

# **`np.append()` in NumPy – Everything You Need to Know**
## **Overview**
`np.append()` is used to add elements to a NumPy array. It **does not modify** the original array but **returns a new array** with the appended values.

---

## **Syntax**
```python
np.append(arr, values, axis=None)
```

## **Parameters**
1. **arr**: The input array.
2. **values**: The values to append (can be a scalar, list, or array).
3. **axis**:
   - `axis=None` (default): Flattens the array and appends values.
   - `axis=0`: Appends along rows (vertical).
   - `axis=1`: Appends along columns (horizontal).

---

## **Appending to a 1D Array**
```python
import numpy as np

arr = np.array([1, 2, 3])
new_arr = np.append(arr, [4, 5, 6])

print(new_arr)  # Output: [1 2 3 4 5 6]
```
- Since `axis=None` by default, `np.append()` **flattens** arrays before appending.

---

## **Appending to a 2D Array**
### **Case 1: Appending Without Specifying Axis (Flattens)**
```python
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
new_arr = np.append(arr_2d, [7, 8, 9])

print(new_arr)  
# Output: [1 2 3 4 5 6 7 8 9] (Flattens into 1D array)
```
**Key Point:** If `axis=None`, it **flattens the 2D array** and appends values.

---

### **Case 2: Appending Along Rows (`axis=0`)**
```python
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
values = np.array([[7, 8, 9]])  # Must match the number of columns

new_arr = np.append(arr_2d, values, axis=0)
print(new_arr)
```
**Output:**
```
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```
- The number of **columns must match** to maintain shape.

---

### **Case 3: Appending Along Columns (`axis=1`)**
```python
arr_2d = np.array([[1, 2], [3, 4]])
values = np.array([[5], [6]])  # Must match number of rows

new_arr = np.append(arr_2d, values, axis=1)
print(new_arr)
```
**Output:**
```
[[1 2 5]
 [3 4 6]]
```
- The number of **rows must match** to maintain shape.

---

## **Handling Shape Mismatch Errors**
Appending along an axis requires matching dimensions:
- If appending **along `axis=0`**, the number of **columns** must match.
- If appending **along `axis=1`**, the number of **rows** must match.

### **Example of Mismatched Shapes (Error)**
```python
arr = np.array([[1, 2, 3], [4, 5, 6]])
values = np.array([7, 8, 9])  # 1D array
np.append(arr, values, axis=0)  # ERROR: Shape mismatch
```
**Solution:** Reshape `values` before appending:
```python
values = np.array([[7, 8, 9]])  # Make it a row
np.append(arr, values, axis=0)  # Works now
```

---

## **Appending to a 3D Array**
```python
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
values = np.array([[[9, 10], [11, 12]]])

new_arr = np.append(arr_3d, values, axis=0)
print(new_arr)
```
- `axis=0`: Appends along depth (adds another matrix).
- `axis=1`: Appends along rows.
- `axis=2`: Appends along columns.

---

## **Performance Consideration**
Appending to NumPy arrays **creates a new array** every time, which is **inefficient for large datasets**. Instead, use:
- **`np.concatenate()`** for efficient joining.
- **Preallocate arrays** if possible.

---

## **Summary**
| Case | Example | Key Point |
|------|---------|-----------|
| 1D Append | `np.append(arr, [4, 5])` | Flattens if `axis=None` |
| 2D Append Row | `np.append(arr_2d, [[7, 8, 9]], axis=0)` | Columns must match |
| 2D Append Column | `np.append(arr_2d, [[5], [6]], axis=1)` | Rows must match |
| 3D Append | `np.append(arr_3d, values, axis=0)` | Appends along depth |

---

This covers everything about **`np.append()`**! 🚀 Let me know if you need any clarifications.

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [22]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print("*" * 50)
print(d)

[[0 1 2]
 [3 4 5]]
**************************************************
[[ 6  7  8]
 [ 9 10 11]]


In [23]:
np.concatenate((c,d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
np.concatenate((c,d),axis = 0) # => row concatenate

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis = 1) # => column concatenate

# **`np.concatenate()` in NumPy – Everything You Need to Know**  

## **Introduction**  
`np.concatenate()` is used to **join two or more arrays** along an existing axis. It is **faster and more memory-efficient** than `np.append()` because it avoids creating unnecessary intermediate arrays.

---

## **Syntax**  
```python
np.concatenate((array1, array2, ...), axis=0)
```
### **Parameters**  
1. **arrays**: A tuple of arrays to concatenate.  
2. **axis (default = 0)**:  
   - `axis=0`: Joins along rows (vertically).  
   - `axis=1`: Joins along columns (horizontally).  
   - `axis=2` (for 3D arrays): Joins along depth.  

---

## **Concatenating 1D Arrays**  
```python
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.concatenate((arr1, arr2))
print(result)  # Output: [1 2 3 4 5 6]
```
### **Key Points:**  
- Since 1D arrays have only one axis, `axis=0` is the only option.  

---

## **Concatenating 2D Arrays**  
### **Case 1: Concatenating Along Rows (`axis=0`)**
```python
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

result = np.concatenate((arr1, arr2), axis=0)
print(result)
```
**Output:**
```
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
```
- **Rows are added (stacked vertically).**
- The **number of columns must match**.

---

### **Case 2: Concatenating Along Columns (`axis=1`)**
```python
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

result = np.concatenate((arr1, arr2), axis=1)
print(result)
```
**Output:**
```
[[1 2 5 6]
 [3 4 7 8]]
```
- **Columns are added (stacked horizontally).**
- The **number of rows must match**.

---

## **Concatenating 3D Arrays**
```python
arr1 = np.array([[[1, 2], [3, 4]]])
arr2 = np.array([[[5, 6], [7, 8]]])

result = np.concatenate((arr1, arr2), axis=0)
print(result)
```
**Output:**
```
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
```
- `axis=0`: Adds a new matrix.
- `axis=1`: Extends rows.
- `axis=2`: Extends columns.

---

## **Why Use `np.concatenate()` Instead of `np.append()`?**
| Feature | `np.concatenate()` | `np.append()` |
|---------|----------------|---------------|
| **Performance** | More efficient | Creates new array each time |
| **Axis Control** | Can concatenate along any axis | Defaults to flattening |
| **Multiple Arrays** | Works with multiple arrays at once | Can append only one array at a time |

👉 **Use `np.concatenate()` for efficiency and structured merging.**  
👉 **Use `np.append()` for small arrays where flattening is needed.**  

---

## **Why Use `np.concatenate()` Instead of Stacking (`np.vstack()`, `np.hstack()`)?**
- `np.concatenate()` gives **more flexibility** to specify an axis.  
- Stacking functions (`vstack`, `hstack`) are **special cases** of `np.concatenate()`.  

| Function | Equivalent `np.concatenate()` |
|----------|----------------------------|
| `np.vstack((a, b))` | `np.concatenate((a, b), axis=0)` |
| `np.hstack((a, b))` | `np.concatenate((a, b), axis=1)` |
| `np.dstack((a, b))` | `np.concatenate((a, b), axis=2)` |

---

## **Use Cases of `np.concatenate()`**
1. **Merging Data from Multiple Sources** (e.g., combining feature sets in ML).
2. **Appending Rows or Columns to Matrices** (e.g., adding new data).
3. **Efficient Data Processing** (avoiding overhead from `np.append()`).
4. **Stacking Image Data** (joining 3D arrays of image channels).

---

## **Summary**
- **`np.concatenate()` is better than `np.append()`** for efficiency.  
- **More flexible than stacking functions** like `vstack`, `hstack`.  
- **Requires matching shapes along the concatenation axis**.  

🚀 **Now you know everything about `np.concatenate()`!** Let me know if you need more explanations! 😊

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html

In [27]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [28]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [34]:
print(a)
print(a.shape)

[35 93 61 60 24 85 69 36 14  5 43 95 45 17 21]
(15,)


In [36]:
print(np.expand_dims(a, axis = 0))
print(np.expand_dims(a, axis = 0).shape)

[[35 93 61 60 24 85 69 36 14  5 43 95 45 17 21]]
(1, 15)


In [37]:
print(np.expand_dims(a, axis = 1))

[[35]
 [93]
 [61]
 [60]
 [24]
 [85]
 [69]
 [36]
 [14]
 [ 5]
 [43]
 [95]
 [45]
 [17]
 [21]]


Useful in row and column vertorization  
Also useful in ML when model expect batch of input but its got a single input then we convert the input into the batch of input using expand_dims

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
a

In [38]:
# find all indices with values greater than 50
np.where(a>50)

(array([ 1,  2,  3,  5,  6, 11], dtype=int64),)

In [41]:
(np.where(b>50))

(array([1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 5, 5, 5], dtype=int64),
 array([3, 0, 1, 2, 3, 0, 1, 3, 0, 1, 0, 1, 2], dtype=int64))

In [43]:
# replace all values with > 50 with 0
np.where(a > 50,0,a)

array([35,  0,  0,  0, 24,  0,  0, 36, 14,  5, 43,  0, 45, 17, 21])

In [44]:
# replace all even number with > 50 with 0
np.where(a % 2 == 0, 0, a)

array([35, 93, 61,  0,  0, 85, 69,  0,  0,  5, 43, 95, 45, 17, 21])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [45]:
a

array([35, 93, 61, 60, 24, 85, 69, 36, 14,  5, 43, 95, 45, 17, 21])

In [46]:
b

array([[ 4, 10, 17, 21],
       [24, 31, 32, 71],
       [80, 89, 80, 92],
       [97, 84, 44, 64],
       [63, 73, 21, 50],
       [93, 95, 65,  8]])

In [47]:
np.argmax(a)

11

In [49]:
np.argmax(b)

array([3, 5, 2, 2], dtype=int64)

In [52]:
np.argmax(b, axis = 0) # column wise

array([3, 5, 2, 2], dtype=int64)

In [53]:
np.argmax(b, axis = 1) # row wise

array([3, 3, 3, 0, 1, 1], dtype=int64)

### np.argmin => same as np.argmax but for min

In [ ]:
a

In [54]:
print(np.argmin(a))

9


### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [55]:
a

array([35, 93, 61, 60, 24, 85, 69, 36, 14,  5, 43, 95, 45, 17, 21])

In [56]:
np.cumsum(a)

array([ 35, 128, 189, 249, 273, 358, 427, 463, 477, 482, 525, 620, 665,
       682, 703])

In [58]:
b

array([[ 4, 10, 17, 21],
       [24, 31, 32, 71],
       [80, 89, 80, 92],
       [97, 84, 44, 64],
       [63, 73, 21, 50],
       [93, 95, 65,  8]])

In [60]:
np.cumsum(b)

array([   4,   14,   31,   52,   76,  107,  139,  210,  290,  379,  459,
        551,  648,  732,  776,  840,  903,  976,  997, 1047, 1140, 1235,
       1300, 1308])

In [61]:
np.cumsum(b, axis = 0) # column wise

array([[  4,  10,  17,  21],
       [ 28,  41,  49,  92],
       [108, 130, 129, 184],
       [205, 214, 173, 248],
       [268, 287, 194, 298],
       [361, 382, 259, 306]])

In [62]:
np.cumsum(b, axis = 1) # row wise

array([[  4,  14,  31,  52],
       [ 24,  55,  87, 158],
       [ 80, 169, 249, 341],
       [ 97, 181, 225, 289],
       [ 63, 136, 157, 207],
       [ 93, 188, 253, 261]])

### np.cumprod => same as np.cumsum but for product

In [63]:
a

array([35, 93, 61, 60, 24, 85, 69, 36, 14,  5, 43, 95, 45, 17, 21])

In [64]:
np.cumprod(a)

array([         35,        3255,      198555,    11913300,   285919200,
       -1466671776,  1878862560, -1080424576,  2053925120,  1679691008,
        -787730688, -1819971328,  -294331136,  -708662016, -1997000448])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [65]:
a

array([35, 93, 61, 60, 24, 85, 69, 36, 14,  5, 43, 95, 45, 17, 21])

In [66]:
np.percentile(a,100) # => same type of percentile as JEE result

95.0

In [67]:
np.percentile(a,0)

5.0

In [68]:
np.percentile(a,50)

43.0

In [69]:
np.median(a)

43.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [70]:
a

array([35, 93, 61, 60, 24, 85, 69, 36, 14,  5, 43, 95, 45, 17, 21])

In [75]:
np.histogram(a, bins = [0,50,100])

(array([9, 6], dtype=int64), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [76]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

upar aisa ouput iss liye aaya hai kyuki phle salary ka correalation salary se hi nikla aur phir experience se  
Then niche experience ka salary se aur phir experience se nikla

image screenshot

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [ ]:
a

In [77]:
items = [10,20,30,40,50,60,70,80,90,100]
np.isin(a,items)

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False])

In [78]:
a[np.isin(a,items)]

array([60])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [79]:
a

array([35, 93, 61, 60, 24, 85, 69, 36, 14,  5, 43, 95, 45, 17, 21])

In [81]:
np.flip(a)

array([21, 17, 45, 95, 43,  5, 14, 36, 69, 85, 24, 60, 61, 93, 35])

In [82]:
b

array([[ 4, 10, 17, 21],
       [24, 31, 32, 71],
       [80, 89, 80, 92],
       [97, 84, 44, 64],
       [63, 73, 21, 50],
       [93, 95, 65,  8]])

In [83]:
np.flip(b)

array([[ 8, 65, 95, 93],
       [50, 21, 73, 63],
       [64, 44, 84, 97],
       [92, 80, 89, 80],
       [71, 32, 31, 24],
       [21, 17, 10,  4]])

In [84]:
np.flip(b, axis = 1) # => row wise flipping

array([[21, 17, 10,  4],
       [71, 32, 31, 24],
       [92, 80, 89, 80],
       [64, 44, 84, 97],
       [50, 21, 73, 63],
       [ 8, 65, 95, 93]])

In [85]:
np.flip(b, axis = 0) # => column wise flipping

array([[93, 95, 65,  8],
       [63, 73, 21, 50],
       [97, 84, 44, 64],
       [80, 89, 80, 92],
       [24, 31, 32, 71],
       [ 4, 10, 17, 21]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [86]:
a

array([35, 93, 61, 60, 24, 85, 69, 36, 14,  5, 43, 95, 45, 17, 21])

In [87]:
np.put(a,[0,1],[110,530])

In [88]:
a

array([110, 530,  61,  60,  24,  85,  69,  36,  14,   5,  43,  95,  45,
        17,  21])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [89]:
a

array([110, 530,  61,  60,  24,  85,  69,  36,  14,   5,  43,  95,  45,
        17,  21])

In [91]:
np.delete(a,[0,1]) # => indices hia yee

array([61, 60, 24, 85, 69, 36, 14,  5, 43, 95, 45, 17, 21])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [92]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [93]:
np.intersect1d(m,n)

array([3, 4, 5])

In [95]:
np.setdiff1d(m,n)

array([1, 2])

In [98]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [100]:
np.in1d(m,3)

array([False, False,  True, False, False])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [101]:
a

array([110, 530,  61,  60,  24,  85,  69,  36,  14,   5,  43,  95,  45,
        17,  21])

In [102]:
np.clip(a, a_min = 25, a_max= 75)

array([75, 75, 61, 60, 25, 75, 69, 36, 25, 25, 43, 75, 45, 25, 25])

joo value clip ke range ke bahar hai usko clip kar dega means replace kar denge given value se