### `Q-1:` Create a random 4x3 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [3]:
# code here
import numpy as np

arr = np.random.randint(1,100,12).reshape(3,4)
arr

array([[45, 72, 21, 99],
       [45, 23, 63, 59],
       [99, 13, 44, 48]])

In [4]:
arr =  [[92, 90, 74],
        [6 , 63, 93],
        [15, 93, 96],
        [70, 60, 48]]
arr = np.array(arr)
arr

array([[92, 90, 74],
       [ 6, 63, 93],
       [15, 93, 96],
       [70, 60, 48]])

In [5]:
# i) Sort this matrix. np.sort()

np.sort(arr, axis = 1)

array([[74, 90, 92],
       [ 6, 63, 93],
       [15, 93, 96],
       [48, 60, 70]])

In [6]:
# ii) Sort this matrix based on values in 2nd column.

sorted_index = np.argsort(arr[:,1])
arr[sorted_index]

array([[70, 60, 48],
       [ 6, 63, 93],
       [92, 90, 74],
       [15, 93, 96]])

In [7]:
# iii) Sort this matrix based on max value in each row.

arr[np.max(arr, axis = 1).argsort()][::-1]


array([[15, 93, 96],
       [ 6, 63, 93],
       [92, 90, 74],
       [70, 60, 48]])

In [8]:
# iv) Sort this matrix based on elements value.

np.sort(arr, axis = None).reshape(3,4)

array([[ 6, 15, 48, 60],
       [63, 70, 74, 90],
       [92, 93, 93, 96]])

### `Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [9]:
# code here
marks = [
    [13, 10, 9, 33],
    [63, 46, 90, 42],
    [39, 76, 13, 29],
    [82, 9, 29, 78],
    [67, 61, 59, 36],
]

marks = np.array(marks)

extra_subject = [41, 87, 72, 36, 92]
extra_subject = np.array(extra_subject).reshape(-1, 1)
# Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec1 = np.array(rec1)
rec2 = [92, 71, 52, 61, 53]
rec2 = np.array(rec2)

# i) Add marks of the extra subject to each student (as a new column)
marks = np.hstack((marks, extra_subject))
print("Marks after adding extra subjects is : ")
print(marks)

# ii) Add two new students marks (each record is already of length 5)
marks = np.vstack((marks, rec1, rec2))
print("Marks after adding two subjects is : ")
print(marks)

# iii)  Add an extra column with the sum of all subject marks (for 5 subjects)
sum_subject = np.sum(marks, axis=1).reshape(-1, 1)
marks = np.hstack((marks, sum_subject))
print("Marks After Adding Total Marks : ")
print(marks)

# iv) Sort the array in non-ascending order (i.e., descending) based on the total marks column
print("Records with Maximum Marks")
marks_index = np.argsort(marks[:,-1])
marks[marks_index][::-1][[0,1]]


Marks after adding extra subjects is : 
[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]]
Marks after adding two subjects is : 
[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]
 [77 83 98 95 89]
 [92 71 52 61 53]]
Marks After Adding Total Marks : 
[[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]
Records with Maximum Marks


array([[ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

### `Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [10]:
# code here
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

print("Unique Row wise:")
print(np.unique(arr,axis=0))


print("Unique col are : ")
print(np.unique(arr,axis=1))




Unique Row wise:
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]
Unique col are : 
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


Let's walk through what happens when you call `np.unique()` on your array with `axis=0` and `axis=1`.

Consider your array:

```python
arr = np.array([[1, 2, 3, 3, 1, 1],
                [0, 9, 1, 2, 8, 8],
                [1, 2, 3, 8, 8, 8],
                [1, 2, 3, 3, 1, 1]])
```

---

### **Unique Rows: `np.unique(arr, axis=0)`**

- **Step 1: Identify Rows as Sequences**

  Each row is treated as a tuple of values:
  
  - Row 0: `(1, 2, 3, 3, 1, 1)`
  - Row 1: `(0, 9, 1, 2, 8, 8)`
  - Row 2: `(1, 2, 3, 8, 8, 8)`
  - Row 3: `(1, 2, 3, 3, 1, 1)`

- **Step 2: Remove Duplicates**

  Notice that row 0 and row 3 are identical. Hence only one of them will be kept.

- **Step 3: Lexicographical Sorting**

  When you call `np.unique`, it returns the unique rows **sorted lexicographically**. This means:
  
  - It compares row elements one by one from left to right.
  - Row 1 starts with `0`, while the other rows start with `1`. Since `0 < 1`, row 1 comes first.
  - Next, it compares the remaining rows. Between row 0 (`(1,2,3,3,1,1)`) and row 2 (`(1,2,3,8,8,8)`), the first three elements are the same. It then compares the fourth element: `3` vs. `8`. Since `3 < 8`, row 0 comes before row 2.

- **Final Unique Rows:**

  Thus, the unique rows returned (in sorted order) are:
  
  ```
  [[0, 9, 1, 2, 8, 8],
   [1, 2, 3, 3, 1, 1],
   [1, 2, 3, 8, 8, 8]]
  ```

---

### **Unique Columns: `np.unique(arr, axis=1)`**

- **Step 1: Identify Columns as Sequences**

  Each column is treated as a tuple (taken from each row):
  
  - Column 0: `(1, 0, 1, 1)`
  - Column 1: `(2, 9, 2, 2)`
  - Column 2: `(3, 1, 3, 3)`
  - Column 3: `(3, 2, 8, 3)`
  - Column 4: `(1, 8, 8, 1)`
  - Column 5: `(1, 8, 8, 1)` — notice this is identical to Column 4.

- **Step 2: Remove Duplicates**

  Since columns 4 and 5 are identical, only one copy is kept.

- **Step 3: Lexicographical Sorting of Columns**

  The unique columns are then sorted by comparing each column as a sequence:
  
  - Compare Column 0 `(1, 0, 1, 1)` with Column 4 `(1, 8, 8, 1)`:  
    - The first elements are equal (`1` and `1`), but the second elements differ (`0` vs. `8`), so Column 0 comes before Column 4.
  - Then the remaining columns (Column 1, Column 2, and Column 3) are compared in a similar manner.
  
  The exact sorted order will be determined by these lexicographical comparisons.

- **Final Unique Columns:**

  For example, the sorted unique columns might appear as (depending on lexicographical order):
  
  ```
  [[1, 2, 3, 1, 3],
   [0, 9, 1, 8, 2],
   [1, 2, 3, 8, 8],
   [1, 2, 3, 1, 3]]
  ```
  
  (The exact order might vary if you check the output, but the key idea is that duplicate columns are removed and the remaining ones are sorted by comparing their entries from top to bottom.)

---

### **Key Points:**

- **Axis Parameter:**  
  - `axis=0` means treat each **row** as an element.
  - `axis=1` means treat each **column** as an element.
  
- **Duplicate Removal:**  
  `np.unique` identifies duplicates by comparing the entire row or column.

- **Lexicographical Sorting:**  
  The unique rows or columns are returned in sorted order, comparing elements in order from the first element onward.

---

This is how NumPy computes unique rows and columns in your array. If you run your code:

```python
import numpy as np

arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

print("Unique Row wise:")
print(np.unique(arr, axis=0))

print("Unique col are : ")
print(np.unique(arr, axis=1))
```

You'll see that duplicate rows (row 0 and row 3) and duplicate columns (columns 4 and 5) are removed, and the remaining unique rows/columns are sorted lexicographically.

### `Q-4:` Flip given 2-D array along both axes at the same time.

In [11]:
# code here
arr =  [[92, 90, 74],
        [6 , 63, 93],
        [15, 93, 96],
        [70, 60, 48]]
arr = np.array(arr)
print(arr)
np.flip(arr, axis = [0,1])



[[92 90 74]
 [ 6 63 93]
 [15 93 96]
 [70 60 48]]


array([[48, 60, 70],
       [96, 93, 15],
       [93, 63,  6],
       [74, 90, 92]])

<center>OR</center>

In [12]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Flip rows and columns simultaneously using slicing
flipped = arr[::-1, ::-1]

print("Original Array:")
print(arr)
print("\nFlipped Array (slicing):")
print(flipped)


Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flipped Array (slicing):
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [13]:
# code here

arr = [[1, 2, 3, 4, 5], [10, -3, 30, 4, 5], [3, 2, 5, -4, 5], [9, 7, 3, 6, 5]]
arr = np.array(arr)
X = 6 

# Find indices of elements larger than X

indices = np.unique(np.where(arr > X)[0])
indices

array([1, 3], dtype=int64)

<center>OR</center>

In [14]:
arr = [[1, 2, 3, 4, 5], [10, -3, 30, 4, 5], [3, 2, 5, -4, 5], [9, 7, 3, 6, 5]]
arr = np.array(arr)
X = 6 

print(arr)
# Find indices of elements larger than X
row_condition = np.any(arr > X, axis=1)
indices = np.where(row_condition)[0]
indices

[[ 1  2  3  4  5]
 [10 -3 30  4  5]
 [ 3  2  5 -4  5]
 [ 9  7  3  6  5]]


array([1, 3], dtype=int64)

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [15]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

arr = np.hstack((arr1, arr2, arr3))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# code here
arr = np.hstack((arr1, arr2, arr3))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<center>OR</center>

In [17]:
np.concatenate([arr1,arr2,arr3])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [18]:
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
print("Original array:")
print(arr)

# Find the minimum and maximum values
min_value = np.min(arr)
max_value = np.max(arr)

# Create a boolean condition for elements that are either the min or the max.
# Since arr is 2D, (arr == min_value) | (arr == max_value) will give a 2D boolean array.
condition = (arr == min_value) | (arr == max_value)

# Use np.where to get the indices where this condition is True.
# For a (1, 200) array, this returns a tuple (row_indices, col_indices).
_, col_indices = np.where(condition)

# Remove the columns that contain the min or max values.
# Since our array is (1, 200), we remove the elements along axis=1.
result = np.delete(arr, col_indices, axis=1)

print("\nArray after removing min and max elements:")
print(result)


Original array:
[[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
  181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
  353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
  921 490 527 972 278 307 840 958 246 449 251 957 103 627 920 824 356 825
  173 323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211
  771 270 308 231 952 514 699 702 433 900 373 318 998 265 503 320 230 324
  922 967 620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930
  325 729 426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528
  395 525 922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859
  618 226 695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748
  291 194 761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207
  883 588]]

Array after removing min and max elements:
[[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
  181 425 790 635 889 818 872 967 277 47

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [19]:
# code here
arr = np.random.randint(100,700,50)
np.cumsum(np.sort(np.clip(arr, 100,200)))

array([ 100,  231,  364,  510,  663,  820, 1020, 1220, 1420, 1620, 1820,
       2020, 2220, 2420, 2620, 2820, 3020, 3220, 3420, 3620, 3820, 4020,
       4220, 4420, 4620, 4820, 5020, 5220, 5420, 5620, 5820, 6020, 6220,
       6420, 6620, 6820, 7020, 7220, 7420, 7620, 7820, 8020, 8220, 8420,
       8620, 8820, 9020, 9220, 9420, 9620])

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [22]:
# code here

arr = np.linspace(0,1,50)
arr = np.round(arr, decimals=3)
print(arr)
print(np.percentile(arr, 0) == np.min(arr))
print(np.percentile(arr, 100) == np.max(arr))
print(np.percentile(arr,51) - np.percentile(arr,50))


[0.    0.02  0.041 0.061 0.082 0.102 0.122 0.143 0.163 0.184 0.204 0.224
 0.245 0.265 0.286 0.306 0.327 0.347 0.367 0.388 0.408 0.429 0.449 0.469
 0.49  0.51  0.531 0.551 0.571 0.592 0.612 0.633 0.653 0.673 0.694 0.714
 0.735 0.755 0.776 0.796 0.816 0.837 0.857 0.878 0.898 0.918 0.939 0.959
 0.98  1.   ]
True
True
0.009800000000000031
