<center><h1>Numpy</h1></center>

### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

#### Why is NumPy fast?

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [4]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [26]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]]) # should have equal number of elements
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [27]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6,17]]) # should have equal number of elements
print(b)
print(type(b))

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [20]:
# 3d np array => tensor

c = np.array( [[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
# dtype => set the data type of the elements

a = np.array([1,2,3], dtype=float)
print(a)

[1. 2. 3.]


In [28]:
# np.arange => behave same like python range

b = np.arange(1,11,2)
print(b)

[1 3 5 7 9]


In [34]:
# with reshape => dimensions of the array set karte hai
b = np.arange(1,13).reshape(2,6)
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [8]:
# with reshape => dimensions of the array set karte hai
b = np.arange(1,17).reshape(2,2,2,2)
print(b)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]


Two ways se array create karte hai  
1- np.array()  
2- np.arange()  
3- np.linspace()  
4- np.zeros()  
5- np.ones()  

In [14]:
# np.ones and np.zeros
np.ones((3,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Benefit of making arrays using np.ones like this ?  
- Fast
- Less memory
- Less code
- More readable
- More efficient
- More pythonic
- Mainly use in DL/ML in NN to intialize weights and biases of the model


screenshot of NN image 630

In [15]:
# np.zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
# np.random

np.random.random((3,4))

array([[0.64861523, 0.67694087, 0.76364327, 0.69923118],
       [0.56443444, 0.35229677, 0.16254912, 0.17689533],
       [0.91589524, 0.85943242, 0.51341549, 0.03433543]])

np.ones, np.zero, np.random all are used in DL/ML

In [4]:
# np.linspace => linear space

np.linspace(-10,10,10) # 1- lower range 2- Upper range 3- No of items you want to generate

# linear space equal length par elements generate karta hia


array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [6]:
# np.linspace => linear space

np.linspace(1,10,10) # 1- lower range 2- Upper range 3- No of items you want to generate


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [7]:
# np.identity

np.identity(3) # 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [11]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2, 2,2)

print(a1)
print("*"*10)
print(a2)
print("*"*10)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
**********
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
**********
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [12]:
# ndim => dimension batata hai

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [15]:
# shape => dimension se kitne rows and column hai yee baata hai

print(a1.shape)
print(a2.shape)
print(a3.shape) # yee (2,2,2) output hai jiska phla 2 ka mtlb hai there are 2 arrays. 
# 2nd and 3rd => 2 rows and 3 columns hia

(10,)
(3, 4)
(2, 2, 2)


In [19]:
# size
print(a1.size) # no of items batata hai
print(a2.size)
print(a3.size)

10
12
8


In [21]:
# itemsize
print(a1.itemsize) # bytes me items ka size bataya hai
print(a2.itemsize)
print(a3.itemsize)

4
8
4


In [23]:
# dtype

print(a1.dtype) # dype data type batata hai
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


### Changing Datatype

In [50]:
# astype => you can change the datatype of an array to something

print(a3.dtype)
a3.astype(np.int64)
print(a3.dtype)

int32
int32


The issue you're encountering happens because the `astype()` method in NumPy returns a new array with the desired data type but **does not modify the original array in place**. In your example:

```python
print(a3.dtype)  # Prints the dtype of the original array, e.g., int32
a3.astype(np.int64)  # Creates a new array with dtype int64, but does not modify a3
print(a3.dtype)  # Still prints the original dtype of a3, e.g., int32
```

To actually change the dtype of the original array, you need to assign the result of `astype()` back to `a3` or to another variable:

```python
a3 = a3.astype(np.int64)
print(a3.dtype)  # Now prints int64, since a3 has been updated
```

This way, `a3` will be converted to the new data type `np.int64`, and you'll see the change reflected in the output.

In [51]:
print(a3.dtype)
a3 = a3.astype(np.int64)
print(a3.dtype)

int32
int64


##### astype() method is used to optimize the memory usage of the array by changing the data type of the elements so that the array consumes less memory.

### Array Operations

In [53]:
a1 = np.arange(12).reshape(3,4)
s2 = np.arange(12,24).reshape(3,4)

In [59]:
# scaler operations

# arithmetic operations
print(a1*2)
print("*"*10)
print(a1 + 2)
print("*"*10)
print(a1-2)
print("*"*10)
print(a1/2)
print("*"*10)
print(a1%2)
print("*"*10)
print(a1**2)


[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
**********
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
**********
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
**********
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
**********
[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]
**********
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [61]:
# relational operations
print(a2 > 5)
print("*"*10)
print(a2 > 15)
print("*"*10)
print(a2 == 15)


[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
**********
[[False False False False]
 [False False False False]
 [False False False False]]
**********
[[False False False False]
 [False False False False]
 [False False False False]]


#### Vector operations

In [63]:
# arithmetic
a1 + a2 # => both shapes are equal we can add them

array([[ 0.,  2.,  4.,  6.],
       [ 8., 10., 12., 14.],
       [16., 18., 20., 22.]])

In [64]:
a1 - a2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
a1 ** a2

array([[1.00000000e+00, 1.00000000e+00, 4.00000000e+00, 2.70000000e+01],
       [2.56000000e+02, 3.12500000e+03, 4.66560000e+04, 8.23543000e+05],
       [1.67772160e+07, 3.87420489e+08, 1.00000000e+10, 2.85311671e+11]])

### Array Functions

In [67]:
# round
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[65., 54., 44.],
       [57., 34., 69.],
       [47., 31., 16.]])

In [68]:
# max/min/sum/prod
print(np.max(a2))
print(np.min(a2))
print(np.sum(a2))
print(np.prod(a2))

85.0
3.0
392.0
49579333516440.0


Numpy gives you very flexibility use can even find max/min/sum/prod of the array as well as max/min of row and column also

In [71]:
# max/min/sum/prod
# 0 => col & 1 => row &
print(np.max(a2, axis= 0))
print(np.min(a2, axis = 0))
print(np.sum(a2, axis = 0))
print(np.prod(a2, axis = 1))

[73. 85. 56.]
[ 3. 27. 39.]
[107. 143. 142.]
[291635.  32643.   5208.]


In [72]:
# mean/median/std/var => whole array as well as col and row wise 
print(np.mean(a2, axis= 0))
print(np.median(a2, axis= 0))
print(np.std(a2, axis= 0))
print(np.var(a2, axis= 0))


[35.66666667 47.66666667 47.33333333]
[31. 31. 47.]
[28.76726535 26.44911257  6.94422222]
[827.55555556 699.55555556  48.22222222]


In [73]:
# trigonometric functions
print(np.sin(a1))

[[ 0.82682868 -0.55878905  0.01770193]
 [ 0.43616476  0.52908269 -0.11478481]
 [ 0.12357312 -0.40403765 -0.28790332]]


In [75]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

print(np.dot(a2,a3))


[[114 120 126]
 [378 400 422]
 [642 680 718]]


Who to calculate the dot product?

In [78]:
# log and exponents
print(np.log(a1))
print("*"*50)
print(np.exp(a1))

[[4.17438727 3.98898405 3.78418963]
 [4.04305127 3.52636052 4.2341065 ]
 [3.8501476  3.4339872  2.77258872]]
**************************************************
[[1.69488924e+28 2.83075330e+23 1.28516001e+19]
 [5.68572000e+24 5.83461743e+14 9.25378173e+29]
 [2.58131289e+20 2.90488497e+13 8.88611052e+06]]


In [86]:
# round/floor/ceil
print(np.round(np.random.random((2,3))*100))
print("*"*50)
print(np.floor(np.random.random((2,3))*100))
print("*"*50)
print(np.ceil(np.random.random((2,3))*100))

[[21. 74.  0.]
 [96. 36. 65.]]
**************************************************
[[90. 85. 92.]
 [95. 15. 69.]]
**************************************************
[[14. 37. 75.]
 [50. 86. 38.]]


### Indexing and Slicing

In [18]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [91]:
# indexing
print(a1[-1]) # last elements ko fetch karnege
print(a2[1,2]) # In 2D =>square brackets ke andr baatana hai ke phle row ko phir columns ko
print(a2[1,0])

9
6
4


In [92]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [95]:
print(a3[1,0,1]) # In 3D => inside the square brackets write 3 numbers first number for which matrix  and 2nd and 3rd value for which row and column

5


In [96]:
print(a3[0,1,0])

2


<center><h4>Slicing</center></h4>

In [97]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
a1[2:7:2] # for 1d same as python slicing

array([2, 4, 6])

In [115]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [112]:
a2[0,:] # first number for column and second number is for row and both number follows 3 slicing

array([0, 1, 2, 3])

In [102]:
a2[:,2]

array([ 2,  6, 10])

In [104]:
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [106]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [113]:
a2[::2,1::2] 

array([[ 1,  3],
       [ 9, 11]])

In [118]:
a2[1:2,::3]

array([[4, 7]])

In [121]:
a2[:2:,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [19]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [6]:
a3[1] # In 3d => there are three comma separated valued all can be sliced :::  

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [7]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [9]:
a3[0:1,1,::] # OR
a3[0,1,::]


array([3, 4, 5])

In [11]:
a3[1,::,1]

array([10, 13, 16])

In [13]:
a3[2,1::,1:]

array([[22, 23],
       [25, 26]])

In [16]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

### Iterating


In [23]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [24]:
a2

for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [22]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [25]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [26]:
for i in np.nditer(a3):
    print(i)    

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [ ]:
# reshape



In [33]:
# Transpose => row ko column, aur column ko row kar deta hai
print(a2)
print("*"*50)
print(np.transpose(a2))
# another syntax of Transpose
a2.T

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
**************************************************
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [32]:
# another syntax of Transpose
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [35]:
# ravel => used for flatten ka ndarray
print(a2.ravel())
print(a3.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


### Stacking

In stacking we can stack 2 or more numpy arrays either vertically or horizontally

In [41]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
print(a4)
print("*"*50)
print(a5)
print("*"*50)
print(np.hstack((a4,a5,a4,a5)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
**************************************************
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
**************************************************
[[ 0  1  2  3 12 13 14 15  0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19  4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23  8  9 10 11 20 21 22 23]]


In [42]:
# vertical stacking
print(a4)
print("*"*50)
print(a5)
print("*"*50)
print(np.hstack((a4,a5,a4,a5)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
**************************************************
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
**************************************************
[[ 0  1  2  3 12 13 14 15  0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19  4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23  8  9 10 11 20 21 22 23]]


Use case=> kbhi kbhi aapke data multiple databases me hota hai toh usko stack karke ek hi database me dalna hota hai aur tb analysis kar skte hai

### Splitting

screeenshot

In [43]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# Horizontal splitting
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [46]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [52]:
# Vertical splitting

print(a5)
np.vsplit(a5,3)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

Spillting ko tb use karte hai jb ek data source se multiple cheeez baanate hai.
Eg: ek collage ka data hai aur multiple branches ka data alag karna chahte ho.