**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [2]:
import numpy as np

### `Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [2]:
# Code here
arr = np.empty(10)
arr[4] = 1
arr

array([3.19172376e-316, 1.77863633e-322, 0.00000000e+000, 0.00000000e+000,
       1.00000000e+000, 1.57434397e+161, 3.27055180e+179, 5.00229395e-090,
       5.04050571e+174, 1.69111913e-306])

<Center>OR</center>

In [4]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### `Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
# Code here
a = int(input("Enter first number : "))
b = int(input("Enter second number : "))

arr = np.random.random((a, b))
print(arr)
print(f"The average of the array is : {np.mean(arr)}")

[[0.87761651 0.69405498 0.45246326 0.86290569]
 [0.27126953 0.29112423 0.98187756 0.84142524]
 [0.40603395 0.81403336 0.90076434 0.67567766]
 [0.62689348 0.36897798 0.60179713 0.46285714]]
The average of the array is :0.6331107523542383


### ` Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [132]:
# Code here


def create_matrix(a, b):
    arr = np.zeros((a, b))
    arr[0] = 1
    arr[-1] = 1
    arr[:, 0] = 1
    arr[:, -1] = 1

    return arr


arr = create_matrix(4,4)
print(arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


### `Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
# Code here

arr = np.linspace(0, 1, 10, endpoint=False)
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


<center>OR</center>


In [ ]:
vector = np.random.uniform(0, 1, 10)

print("Generated vector using random uniform:", vector)

Generated vector using random uniform: [0.65268375 0.55767956 0.40708466 0.06674903 0.87103202 0.24627858
 0.5774888  0.27407173 0.34878231 0.98215984]


### `Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [24]:
# Code here

arr = np.identity(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# So we cannot create a identity matrix of 3*4 bcz identity matrix is square in shape

### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
arr = np.zeros((5, 5), dtype=np.int32)
arr += np.arange(5)
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
# code here

# Generate random vector of shape (10, 2) with integers in the range 1 to 100
arr = np.random.randint(1, 101, size=(10, 2))
print("Random points:")
print(arr)

# Given point
point = np.array([2, 3])
print("Given point : ")
print(point)

# # Calculate the Euclidean distance from the given point to each point in the random vector
distances = np.sqrt(np.sum((arr - point) ** 2, axis=1))

# Convert the distances to integers
distances = distances.astype(np.int32)

print("Distances:")
print(distances)

Random points:
[[ 8 44]
 [51 78]
 [80 63]
 [50 41]
 [46 62]
 [41 95]
 [ 8 66]
 [68 88]
 [26  7]
 [18 39]]
Given point : 
[2 3]
Distances:
[ 41  89  98  61  73  99  63 107  24  39]


### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
# Code here

count = 0
flag = False
for i in range(6):
    for j in range(7):
        for k in range(8):
            count += 1
            if count == 100:
                print(f"({i}, {j}, {k})")
                flag = True
                break
        if flag:
            break
    if flag:
        break

(1, 5, 3)


<center>OR</center>

In [ ]:
index = 99
shape = (6, 7, 8)

ans_index = np.unravel_index(index, shape)
ans_index

(1, 5, 3)

In [ ]:
# verification

arr = np.zeros((6, 7, 8))

print(arr)

arr[1, 5, 3] = 1
print("*" * 100)
print(arr)

[[[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
# Code here

input_line = input("Enter space-separated numbers: ")

numbers = list(map(int, input_line.split()))

np_array = np.array(numbers)

reversed_array = np_array[::-1].astype(float)

print(reversed_array)

[-10.  -8.   4.   3.   2.   1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [32]:
# Code here

arr = np.array([])

print(len(arr))

0


<center>OR</center>

In [34]:
print(arr.size)

0


In the context of NumPy arrays, both `len()` and `arr.size` can be used to get the size of an array, but they serve different purposes and behave differently depending on the type of array you're working with. Let's explore both in detail:

### 1. **`len()`**
- **`len(arr)`** returns the length of the first dimension (axis 0) of the array. For a 1D array, this gives the total number of elements. However, for a multi-dimensional array, it will only give you the number of elements along the first axis (the number of rows in a 2D array, for example).
- **For 1D arrays**: `len()` will give the total number of elements.
- **For 2D or higher-dimensional arrays**: `len()` only gives the size of the first dimension (rows for a 2D array).

### 2. **`arr.size`**
- **`arr.size`** returns the **total number of elements** in the array, regardless of its shape. It calculates the product of the dimensions of the array. This works universally for all array shapes.
  
### Example:

```python
import numpy as np

# Create an empty 1D array
arr = np.array([])

print("len(arr):", len(arr))        # Length of the first dimension (rows)
print("arr.size:", arr.size)        # Total number of elements
```

#### Output:
```
len(arr): 0
arr.size: 0
```

Both `len(arr)` and `arr.size` return `0` for an empty array because there are no elements in the array. However, the difference becomes more noticeable with non-empty arrays.

### Example with 2D array:

```python
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("len(arr_2d):", len(arr_2d))      # Length of the first dimension (rows)
print("arr_2d.size:", arr_2d.size)      # Total number of elements
```

#### Output:
```
len(arr_2d): 2
arr_2d.size: 6
```

- **`len(arr_2d)`** gives the number of rows (which is `2`), because it looks at the first dimension.
- **`arr_2d.size`** gives the total number of elements (`6`), which is the product of the dimensions (2 rows * 3 columns).

### **Which one is better?**

- **`len()`** is more useful when you are specifically interested in the size of the first dimension (e.g., number of rows in a 2D array).
- **`arr.size`** is better if you want to get the total number of elements in the array, regardless of the number of dimensions.

For general use, **`arr.size`** is more versatile because it works consistently across arrays of any shape, while `len()` is limited to the first dimension.

### Conclusion:
- **`arr.size`** is the better option when you need the total number of elements in the array.
- **`len(arr)`** is useful when you specifically need the length of the first dimension (i.e., the number of rows in a 2D array).

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
# Code here


def softmax(arr):
    if not isinstance(arr, np.ndarray):
        raise TypeError("Input must be a numpy array.")
    elif arr.ndim != 1:
        raise ValueError("Input must be a 1D numpy array.")

    return np.exp(arr) / np.sum(np.exp(arr))


arr = np.array(
    [86.03331084, 37.7285648, 48.64908087, 87.16563062, 38.40852563, 37.20006318]
)

softmax_output = softmax(arr)
print("Softmax")
print(softmax_output)

Softmax
[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
# Code here


def vstacking(*arrays):
    """Stacks the input arrays vertically."""

    for arr in arrays:
        if not isinstance(arr, np.ndarray):
            raise TypeError("All inputs must be numpy arrays.")
    return np.vstack(arrays)


a = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])

b = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])

c = np.array(
    [
        [0.10117373, 0.1677244, 0.73764059, 0.83166097, 0.48985695],
        [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593],
    ]
)

result_array = vstacking(a, b, c)
print(result_array)

[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
# Code here


def date_array(start, end):
    if not isinstance(start, str) and isinstance(end, str):
        raise TypeError("Both inputs must be strings in the format YYYY-MM-DD")

    try:
        start_date = np.datetime64(start, "D")
        end_date = np.datetime64(end, "D")
    except Exception as e:
        raise ValueError("Invalid date format. Use YYYY-MM-DD") from e
    else:
        dates = np.arange(
            start_date, end_date + np.timedelta64(1, "D"), np.timedelta64(1, "D")
        )

    return dates


start = "2020-09-15"
end = "2020-09-25"
print(date_array(start, end))

['2020-09-15' '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19'
 '2020-09-20' '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24'
 '2020-09-25']


Below is one complete solution using NumPy only. This solution does the following:

1. **Validates Input:**  
   - Checks that both inputs are strings.
   - Attempts to convert the strings to NumPy datetime64 objects with day resolution.
   - Optionally verifies that both dates are in the same year (as per the problem requirement).

2. **Creates the Date Array:**  
   - Uses `np.arange` with a step of 1 day (`np.timedelta64(1, 'D')`) from the start date to the end date + 1 day (since `arange` is exclusive on the stop value).
   - Converts the resulting array to strings using `np.datetime_as_string`.

Here’s the code:

```python
import numpy as np

def date_array(start, end):
    # Ensure both inputs are strings
    if not (isinstance(start, str) and isinstance(end, str)):
        raise TypeError("Both inputs must be strings in the format YYYY-MM-DD")
    
    try:
        # Convert the input strings to numpy datetime64 objects (with day resolution)
        start_date = np.datetime64(start, 'D')
        end_date = np.datetime64(end, 'D')
    except Exception as e:
        raise ValueError("Invalid date format. Use YYYY-MM-DD") from e
    
    # Optional: ensure the dates are in the same year
    if start_date.astype('datetime64[Y]') != end_date.astype('datetime64[Y]'):
        raise ValueError("Both dates must be in the same year.")
    
    # Create an array of dates from start_date to end_date (inclusive)
    dates = np.arange(start_date, end_date + np.timedelta64(1, 'D'), np.timedelta64(1, 'D'))
    
    # Convert the datetime64 array to an array of strings (if needed)
    return np.datetime_as_string(dates, unit='D')


# Example usage:

print(date_array('2020-09-15', '2020-09-25'))
# Output:
# ['2020-09-15' '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19'
#  '2020-09-20' '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24'
#  '2020-09-25']

print(date_array('2022-12-01', '2022-12-06'))
# Output:
# ['2022-12-01' '2022-12-02' '2022-12-03' '2022-12-04' '2022-12-05'
#  '2022-12-06']

print(date_array('2020-11-25', '2020-11-30'))
# Output:
# ['2020-11-25' '2020-11-26' '2020-11-27' '2020-11-28' '2020-11-29'
#  '2020-11-30']
```

### Explanation

- **Input Validation:**  
  The function first ensures that both `start` and `end` are strings. If not, it raises a `TypeError`.

- **Date Conversion:**  
  The strings are converted into `np.datetime64` objects (with unit `'D'` for day). If conversion fails (e.g., due to wrong format), a `ValueError` is raised.

- **Same-Year Check:**  
  The dates are converted to year-level resolution (using `astype('datetime64[Y]')`) to ensure they belong to the same year. If not, a `ValueError` is raised.

- **Date Range Generation:**  
  The function uses `np.arange` to generate dates from `start_date` up to (and including) `end_date`. Since `np.arange` is exclusive on the end, we add one day to include the end date.

- **Conversion to String:**  
  Finally, `np.datetime_as_string` converts the datetime array into an array of strings.

This solution uses only NumPy to perform all operations and meets the requirements of the question. Enjoy coding!

`numpy.datetime64` is a NumPy data type designed to represent dates and times in a compact and efficient way, especially when you need to perform vectorized operations over large datasets. Let’s break down its features and how it works, particularly in the context of the code you saw:

---

### **1. What is `numpy.datetime64`?**

- **Representation:**  
  `numpy.datetime64` stores dates (and optionally times) in a fixed, precise format. Unlike Python’s built-in `datetime` module, it is implemented in C, which makes it very efficient for array operations.

- **Precision:**  
  When you create a `numpy.datetime64` object, you can specify the precision (or “unit”) of the time data. Common units include:
  - **`'Y'`** for year,
  - **`'M'`** for month,
  - **`'D'`** for day,
  - **`'h'`** for hour,
  - **`'m'`** for minute,
  - **`'s'`** for second, etc.

  For example, if you write:
  ```python
  np.datetime64('2020-09-15', 'D')
  ```
  it represents September 15, 2020, with a day-level resolution (ignoring any time information).

---

### **2. How do you create and use `numpy.datetime64`?**

- **Creation:**  
  You can convert a date string to a `datetime64` object by passing the string to `np.datetime64`:
  ```python
  date = np.datetime64('2020-09-15')
  ```
  By default, if you don't specify a unit, NumPy uses a default (often `'D'` for dates).

- **Arithmetic with Dates:**  
  You can perform arithmetic with `numpy.datetime64` objects. For example, to add one day, you use a `numpy.timedelta64` object:
  ```python
  one_day = np.timedelta64(1, 'D')
  next_day = date + one_day  # This gives you 2020-09-16 as a datetime64 object.
  ```

- **Generating Ranges of Dates:**  
  One of the powerful features is using `np.arange` to generate a range of dates. For example:
  ```python
  start_date = np.datetime64('2020-09-15', 'D')
  end_date = np.datetime64('2020-09-25', 'D')
  dates = np.arange(start_date, end_date + np.timedelta64(1, 'D'), np.timedelta64(1, 'D'))
  ```
  Here, `np.arange` creates an array of dates starting from `start_date` up to (but not including) `end_date + 1 day`. This ensures the end date is included in the resulting array.

- **Conversion to String:**  
  Often, you might want to display these dates as strings. You can use `np.datetime_as_string` to convert the `datetime64` array back into an array of formatted strings:
  ```python
  dates_str = np.datetime_as_string(dates, unit='D')
  ```

---

### **3. How Does This Relate to Your Code?**

In your function `date_array`, the process is:
1. **Input Validation:**  
   The function ensures that the inputs are strings in the expected format.

2. **Conversion:**  
   It converts the input strings into `numpy.datetime64` objects using a day-level resolution (the `'D'` unit). This makes sure that only the date part is used, not the time.

3. **Generating the Range:**  
   `np.arange` is used with a step of one day (`np.timedelta64(1, 'D')`). This creates an array of dates from the start date up to and including the end date.

4. **Final Conversion:**  
   The resulting array of `datetime64` objects is converted to strings for easier reading.

---

### **Example in Context:**

```python
import numpy as np

def date_array(start, end):
    # Convert input strings to datetime64 objects with day precision
    start_date = np.datetime64(start, 'D')
    end_date = np.datetime64(end, 'D')
    
    # Generate dates from start_date to end_date (inclusive)
    dates = np.arange(start_date, end_date + np.timedelta64(1, 'D'), np.timedelta64(1, 'D'))
    
    # Convert the datetime64 array to an array of strings
    return np.datetime_as_string(dates, unit='D')

# Usage:
result = date_array('2020-09-15', '2020-09-25')
print(result)
```

This will output:
```
['2020-09-15' '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19'
 '2020-09-20' '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24'
 '2020-09-25']
```

---

### **Summary**

- **`numpy.datetime64`** is a specialized data type for handling dates and times efficiently in NumPy.
- It supports arithmetic operations when paired with `numpy.timedelta64`.
- You can create ranges of dates using functions like `np.arange`.
- In your code, it allows you to convert date strings into date objects, generate a sequence of dates, and then convert that sequence back to readable strings.

This should help clarify how `numpy.datetime64` works and how it is used in the provided code!

### `Q-14:` Subtract the mean of each row from a matrix.

In [ ]:
# code here

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

mean_matrix = np.mean(matrix, axis=1, keepdims=True)
print(mean_matrix)

matrix = matrix - mean_matrix
matrix

[[2.]
 [5.]
 [8.]]


array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

The issue is with the shape of `mean_matrix`. When you compute the mean without keeping dimensions, you get a 1D array of shape `(3,)` rather than a 2D column vector of shape `(3,1)`. In your subtraction, NumPy will broadcast the 1D array across the columns, subtracting the same three values from every row rather than subtracting each row's mean from that row.

To fix this, you should compute the row means with `keepdims=True` so that the resulting array retains a second dimension and can be broadcast correctly.

For example, change:

```python
mean_matrix = np.mean(matrix, axis=1)
```

to:

```python
mean_matrix = np.mean(matrix, axis=1, keepdims=True)
```

Then, subtracting will work as intended:

```python
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

mean_matrix = np.mean(matrix, axis=1, keepdims=True)
print("Row means:\n", mean_matrix)

result = matrix - mean_matrix
print(result)
```

This will yield the desired output:

```
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
```

In summary, the code is failing because of the broadcasting issue due to the wrong shape of `mean_matrix`.

### `Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
# Code here

def swap_column(arr):
    arr[:,[0,1]] = arr[:,[1,0]]
    return arr 
    

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Before : ")
print(arr)
print("After : ")
swap_column(arr)

Before : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
After : 


array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])

### `Q-16:` Replace odd elements in arrays with -1.

In [98]:
# Code here 
arr = np.arange(20).reshape(-1,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [99]:
arr[arr % 2 != 0] = -1
print(arr)

[[ 0 -1  2 -1]
 [ 4 -1  6 -1]
 [ 8 -1 10 -1]
 [12 -1 14 -1]
 [16 -1 18 -1]]


### `Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [97]:
# Code here
a = np.array([6, 3, 1, 5, 8])
b = np.array([3, 2, 1, 7, 2])

c = np.max( (a,b), axis = 0)
c

array([6, 3, 1, 7, 8])

### `Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [102]:
# Given
arr1 = np.random.randint(low=1, high=10000, size=40).reshape(8, 5)
arr1

array([[6938, 9727, 3420, 4316, 7796],
       [6826,  443, 2028, 8787, 6048],
       [2922, 7319, 6775, 3130, 4450],
       [3986, 9199, 2324, 7599, 7925],
       [5384, 7527, 3159, 1763, 8348],
       [7597, 1342, 1538, 2291, 1153],
       [2980, 5303, 3047, 9820, 2099],
       [7275, 9782, 8566, 3652,  104]])

In [104]:
# Code here

arr1[:,::2]

array([[6938, 3420, 7796],
       [6826, 2028, 6048],
       [2922, 6775, 4450],
       [3986, 2324, 7925],
       [5384, 3159, 8348],
       [7597, 1538, 1153],
       [2980, 3047, 2099],
       [7275, 8566,  104]])

In [114]:
def normalized(arr):
    return (arr - np.min(arr)) / (np.max(arr) - np.min(arr))

normalized(arr1)

array([[0.70337587, 0.99042816, 0.34129271, 0.43351173, 0.79168382],
       [0.6918485 , 0.0348909 , 0.19802388, 0.89368053, 0.61177439],
       [0.29003705, 0.74258954, 0.68659942, 0.31144504, 0.44730342],
       [0.39954714, 0.93608481, 0.22848909, 0.77140799, 0.80496089],
       [0.54343351, 0.76399753, 0.31442981, 0.17074928, 0.84849732],
       [0.77120214, 0.12741869, 0.1475916 , 0.22509263, 0.10796624],
       [0.29600659, 0.53509675, 0.30290243, 1.        , 0.20533141],
       [0.73806093, 0.99608893, 0.87093454, 0.36517085, 0.        ]])

### `Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [118]:
# Code here

input_num = list(map(int,input("Enter number separated by spaces").split( )))
arr = np.array(input_num)

n = int(input("Enter a number to find the nth largest number in the array : "))

sorted_array = np.sort(arr)
sorted_array[n]


12

### `Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [130]:
# code here

a = np.array([1,2,3])
result_array = np.concatenate((np.repeat(a,np.size(a)),np.tile(a,np.size(a))))
result_array

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])